matrix:
  include:
    - language: rust
      rust: 1.34.0
      cache: cargo

      script:
        - cargo test --all --locked --verbose

    - language: rust
      rust: stable
      cache: cargo

      install:
        - rustup component add rustfmt
        - rustup component add clippy

      script: ./bin/run-tests.sh