[package]
name = "rojo"
version = "0.5.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
description = "Enables professional-grade development tools for Roblox developers"
license = "MPL-2.0"
repository = "https://github.com/rojo-rbx/rojo"
edition = "2018"

exclude = [
    "/plugin/**",
    "/test-projects/**",
]

[workspace]
members = [
    "rojo-test",
]

[profile.dev]
opt-level = 1

[lib]
name = "librojo"
path = "src/lib.rs"

[[bin]]
name = "rojo"
path = "src/bin.rs"

[dependencies]
clap = "2.27"
crossbeam-channel = "0.3.9"
csv = "1.0"
env_logger = "0.6"
failure = "0.1.3"
futures = "0.1"
hyper = "0.12"
reqwest = "0.9.20"
jod-thread = "0.1.0"
log = "0.4"
maplit = "1.0.1"
notify = "4.0"
rbx_binary = "0.4.1"
rbx_dom_weak = "1.9.0"
rbx_reflection = "3.1.388"
rbx_xml = "0.11.0"
regex = "1.0"
ritz = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.7", features = ["v4", "serde"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.6.2"

[dev-dependencies]
lazy_static = "1.2"
paste = "0.1"
pretty_assertions = "0.6.1"
tempfile = "3.0"
walkdir = "2.1"
