site_name: Rojo Documentation
repo_name: LPGhatguy/rojo
repo_url: https://github.com/LPGhatguy/rojo

theme:
  name: material
  palette:
    primary: 'Red'
    accent: 'Red'

nav:
  - Home: index.md
  - Why Rojo?: why-rojo.md
  - Installation: installation.md
  - Creating a Place with Rojo: creating-a-place.md
  - Migrating from 0.4.x to 0.5.x: migrating-to-epiphany.md
  - Project Format: project-format.md
  - Sync Details: sync-details.md
  - Rojo Internals:
    - Internals Overview: internals/overview.md

extra_css:
  - extra.css

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true