name: CI

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [stable, 1.69.0]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust_version }}
        override: true
        profile: minimal

    - name: Setup Aftman
      uses: ok-nick/setup-aftman@v0.3.0
      with:
        version: 'v0.2.7'

    - name: Build
      run: cargo build --locked --verbose

    - name: Test
      run: cargo test --locked --verbose

  lint:
    name: Rustfmt and Clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Setup Aftman
      uses: ok-nick/setup-aftman@v0.3.0
      with:
        version: 'v0.2.7'

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy

  Changelog:
    name: Changelog Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Changelog check
    
      uses: Zomzog/changelog-checker@v1.3.0
      with:
        fileName: CHANGELOG.md 
        noChangelogLabel: no changelog
        checkNotification: Simple
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

